import type { SubgraphDetail } from "@secondlayer/shared/schemas";
import { toPascalCase } from "../utils/case-conversion";
import { formatCode } from "../utils/format.ts";

/**
 * Generates a typed client `.ts` file for a deployed subgraph.
 *
 * The output file:
 *  - exports typed row interfaces for each table
 *  - exports a `createClient(options?)` factory
 *  - re-exports `Client` type = `InferSubgraphClient<typeof _schema>`
 */
export async function generateSubgraphConsumer(
	subgraphName: string,
	detail: SubgraphDetail,
): Promise<string> {
	const tables = Object.entries(detail.tables);

	type ColMeta = { type: string; nullable?: boolean };
	type TableDef = {
		columns: Record<string, ColMeta>;
		endpoint: string;
		rowCount: number;
		example: string;
	};

	// Row types are ALIASES over the emitted `_schema`, never a second
	// hand-written mapping. The old local map answered `uint` with `number`
	// while the runtime client answered `bigint` — the generated interface
	// did not compile against the client it shipped beside, and silently
	// truncated uint128 above 2^53. One source of truth now: add a
	// `ColumnType` and every generator follows automatically.
	const rowInterfaces = tables.map(([tableName]: [string, TableDef]) => {
		const typeName = `${toPascalCase(tableName)}Row`;
		return `export type ${typeName} = InferTableRow<(typeof _schema)['schema'][${JSON.stringify(tableName)}]>;`;
	});

	// Build _schema const — must match InferSubgraphClient's expected shape
	const schemaColumns = tables.map(
		([tableName, tableDef]: [string, TableDef]) => {
			const cols = Object.entries(tableDef.columns)
				.filter(([colName]) => !colName.startsWith("_"))
				.map(([colName, colMeta]: [string, ColMeta]) => {
					const nullable = colMeta.nullable ? ", nullable: true" : "";
					return `        ${colName}: { type: '${colMeta.type}'${nullable} }`;
				})
				.join(",\n");
			return `    ${tableName}: {\n      columns: {\n${cols}\n      }\n    }`;
		},
	);

	const schemaBlock = schemaColumns.join(",\n");

	const code = `
// Auto-generated by secondlayer. Do not edit.
import { getSubgraph } from '@secondlayer/sdk';
import type { InferSubgraphClient, InferTableRow } from '@secondlayer/subgraphs';

const _schema = {
  name: '${subgraphName}',
  schema: {
${schemaBlock}
  }
} as const;

${rowInterfaces.join("\n")}

export type Client = InferSubgraphClient<typeof _schema>;

export function createClient(options?: { apiKey?: string; baseUrl?: string }): Client {
  return getSubgraph(_schema, options ?? {});
}
`.trimStart();

	return formatCode(code);
}
