import type { ViewDetail } from "@secondlayer/shared/schemas";
import { formatCode } from "../utils/format.ts";

/**
 * Generates a typed client `.ts` file for a deployed view.
 *
 * The output file:
 *  - exports typed row interfaces for each table
 *  - exports a `createClient(options?)` factory
 *  - re-exports `Client` type = `InferViewClient<typeof _schema>`
 */
export async function generateViewConsumer(
  viewName: string,
  detail: ViewDetail,
): Promise<string> {
  const tables = Object.entries(detail.tables);

  type ColMeta = { type: string; nullable?: boolean };
  type TableDef = { columns: Record<string, ColMeta>; endpoint: string; rowCount: number; example: string };

  // Build row interfaces
  const rowInterfaces = tables.map(([tableName, tableDef]: [string, TableDef]) => {
    const typeName = toPascalCase(tableName) + "Row";
    const fields = Object.entries(tableDef.columns)
      .map(([colName, colMeta]: [string, ColMeta]) => {
        const tsType = viewTypeToTS(colMeta.type);
        const optional = colMeta.nullable ? "?" : "";
        return `  ${colName}${optional}: ${tsType};`;
      })
      .join("\n");
    return `export interface ${typeName} {\n${fields}\n}`;
  });

  // Build _schema const — must match InferViewClient's expected shape
  const schemaColumns = tables.map(([tableName, tableDef]: [string, TableDef]) => {
    const cols = Object.entries(tableDef.columns)
      .filter(([colName]) => !colName.startsWith("_"))
      .map(([colName, colMeta]: [string, ColMeta]) => {
        const nullable = colMeta.nullable ? ", nullable: true" : "";
        return `        ${colName}: { type: '${colMeta.type}'${nullable} }`;
      })
      .join(",\n");
    return `    ${tableName}: {\n      columns: {\n${cols}\n      }\n    }`;
  });

  const schemaBlock = schemaColumns.join(",\n");

  const code = `
// Auto-generated by secondlayer. Do not edit.
import { getView } from '@secondlayer/sdk';
import type { InferViewClient } from '@secondlayer/views';

${rowInterfaces.join("\n\n")}

const _schema = {
  name: '${viewName}',
  schema: {
${schemaBlock}
  }
} as const;

export type Client = InferViewClient<typeof _schema>;

export function createClient(options?: { apiKey?: string; baseUrl?: string }): Client {
  return getView(_schema, options ?? {});
}
`.trimStart();

  return formatCode(code);
}

function toPascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

/**
 * Maps column type strings from the API to TypeScript types.
 * Covers both view ColumnType values and system column PG types.
 */
function viewTypeToTS(type: string): string {
  switch (type) {
    case "uint":
    case "int":
    case "bigint":
    case "serial":
      return "number";
    case "text":
    case "principal":
    case "timestamp":
      return "string";
    case "boolean":
      return "boolean";
    case "jsonb":
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}
