import { describe, expect, test } from "bun:test";
import {
	type PrintPayloadSource,
	generatePrintPayloadTypes,
} from "./print-payload-types.ts";

const CONTRACT = "SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-registry";

const SOURCES: PrintPayloadSource[] = [
	{
		sourceName: "completedDeposit",
		contractId: CONTRACT,
		topics: [
			{
				topic: "completed-deposit",
				non_tuple: false,
				fields: [
					{ camel_name: "amount", ts_type: "bigint", always_present: true },
					{
						camel_name: "bitcoinTxid",
						ts_type: "string",
						always_present: true,
					},
					{
						camel_name: "sweepTxid",
						ts_type: "string | null",
						always_present: false,
					},
				],
			},
		],
	},
	{
		sourceName: "registryEvents",
		contractId: CONTRACT,
		topics: [
			{
				topic: "withdrawal-create",
				non_tuple: false,
				fields: [
					{ camel_name: "amount", ts_type: "bigint", always_present: true },
				],
			},
			{
				topic: "withdrawal-reject",
				non_tuple: false,
				fields: [
					{ camel_name: "requestId", ts_type: "bigint", always_present: true },
				],
			},
		],
	},
];

describe("generatePrintPayloadTypes", () => {
	test("emits a generated header", () => {
		const out = generatePrintPayloadTypes({ sources: SOURCES });
		expect(out).toContain(
			"// Generated by `sl subgraphs codegen --payloads`. Do not edit by hand.",
		);
	});

	test("one interface per source x topic with literal topic + typed data", () => {
		const out = generatePrintPayloadTypes({ sources: SOURCES });
		expect(out).toContain(
			"export interface CompletedDepositCompletedDepositPayload {",
		);
		expect(out).toContain("contractId: string;");
		expect(out).toContain("topic: 'completed-deposit';");
		expect(out).toContain("amount: bigint;");
		expect(out).toContain("bitcoinTxid: string;");
	});

	test("non-always_present fields become optional properties", () => {
		const out = generatePrintPayloadTypes({ sources: SOURCES });
		expect(out).toContain("sweepTxid?: string | null;");
	});

	test("per-source discriminated union alias", () => {
		const out = generatePrintPayloadTypes({ sources: SOURCES });
		expect(out).toContain(
			"export type CompletedDepositPayload = CompletedDepositCompletedDepositPayload;",
		);
		expect(out).toContain(
			"export type RegistryEventsPayload = RegistryEventsWithdrawalCreatePayload | RegistryEventsWithdrawalRejectPayload;",
		);
	});

	test("'*' pseudo-topic → Wildcard name, string topic, unknown data", () => {
		const out = generatePrintPayloadTypes({
			sources: [
				{
					sourceName: "events",
					contractId: CONTRACT,
					topics: [{ topic: "*", non_tuple: true, fields: [] }],
				},
			],
		});
		expect(out).toContain("export interface EventsWildcardPayload {");
		// Runner always yields a string topic (possibly ""), never null.
		expect(out).toContain("topic: string;");
		expect(out).not.toContain("string | null");
		expect(out).toContain("data: Record<string, unknown>;");
		expect(out).toContain("export type EventsPayload = EventsWildcardPayload;");
	});

	test("rejects empty input", () => {
		expect(() => generatePrintPayloadTypes({ sources: [] })).toThrow();
		expect(() =>
			generatePrintPayloadTypes({
				sources: [{ sourceName: "a", contractId: CONTRACT, topics: [] }],
			}),
		).toThrow();
	});
});
