/**
 * Print payload .d.ts generator — emits per-topic payload interfaces and a
 * per-source discriminated union from a contract's empirically inferred print
 * topics (the /v1/index/contracts/:id/print-schema response). Pure string
 * templating: callers (CLI `sl subgraphs codegen --payloads`) fetch the
 * schema and pass the topics in.
 */

/** One inferred field of a topic — structural subset of the print-schema response. */
export interface PrintPayloadField {
	/** What handlers see on `event.data`. */
	camel_name: string;
	/** Decoded handler value type (uint→bigint, buffer→string, …). */
	ts_type: string;
	/** Present in 100% of the topic's samples — otherwise the key is optional. */
	always_present: boolean;
}

/** One inferred topic — structural subset of the print-schema response. */
export interface PrintPayloadTopic {
	/** Tuple `topic` field; "*" pseudo-topic for absent/non-tuple prints. */
	topic: string;
	non_tuple?: boolean;
	fields: PrintPayloadField[];
}

export interface PrintPayloadSource {
	/** Subgraph source key — prefixes the generated type names. */
	sourceName: string;
	/** Full contract identifier, e.g. SP….contract-name. */
	contractId: string;
	/** Topics this source can receive (caller filters by the source's `topic` pin). */
	topics: PrintPayloadTopic[];
}

export interface PrintPayloadTypesInput {
	sources: PrintPayloadSource[];
}

const IDENT_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** Object-type key — quoted when not a valid identifier. */
function key(k: string): string {
	return IDENT_RE.test(k) ? k : `'${k}'`;
}

/** kebab/camel/anything → PascalCase type-name fragment. */
function pascalCase(str: string): string {
	const cleaned = str
		.replace(/[^A-Za-z0-9]+([A-Za-z0-9])/g, (_, c: string) => c.toUpperCase())
		.replace(/[^A-Za-z0-9]/g, "");
	if (!cleaned) return "";
	return cleaned[0].toUpperCase() + cleaned.slice(1);
}

/** Type-name fragment for a topic; "*" pseudo-topic → "Wildcard". */
function topicTypeName(topic: string): string {
	return pascalCase(topic) || "Wildcard";
}

function dataType(topic: PrintPayloadTopic): string {
	if (topic.non_tuple || topic.fields.length === 0) {
		// Non-tuple prints have no inferable shape.
		return "Record<string, unknown>";
	}
	const fields = topic.fields
		.map(
			(f) =>
				`    ${key(f.camel_name)}${f.always_present ? "" : "?"}: ${f.ts_type};`,
		)
		.join("\n");
	return `{\n${fields}\n  }`;
}

/**
 * Emit a .d.ts with one `<SourceName><TopicName>Payload` interface per
 * source × topic plus a `<SourceName>Payload` discriminated union per source.
 */
export function generatePrintPayloadTypes(
	input: PrintPayloadTypesInput,
): string {
	if (input.sources.length === 0) {
		throw new Error("print payload types require at least one source");
	}
	const blocks: string[] = [
		"// Generated by `sl subgraphs codegen --payloads`. Do not edit by hand.",
		"// Empirical print payload types inferred from observed on-chain events.",
	];
	for (const source of input.sources) {
		if (source.topics.length === 0) {
			throw new Error(
				`print payload source "${source.sourceName}" has no topics`,
			);
		}
		const sourcePrefix = pascalCase(source.sourceName) || "Source";
		const interfaceNames: string[] = [];
		for (const topic of source.topics) {
			const name = `${sourcePrefix}${topicTypeName(topic.topic)}Payload`;
			interfaceNames.push(name);
			// "*" groups prints with no (string) topic — no literal to discriminate
			// on, but the runner always yields a string (possibly "").
			const topicType = topic.topic === "*" ? "string" : `'${topic.topic}'`;
			blocks.push(
				`/** \`${source.sourceName}\` — ${source.contractId}, topic "${topic.topic}". */
export interface ${name} {
  contractId: string;
  topic: ${topicType};
  data: ${dataType(topic)};
}`,
			);
		}
		blocks.push(
			`/** Every payload the \`${source.sourceName}\` source can receive. */
export type ${sourcePrefix}Payload = ${interfaceNames.join(" | ")};`,
		);
	}
	return `${blocks.join("\n\n")}\n`;
}
