import type { Database } from "./types.ts";

// The physical source-table columns the public read API (packages/api) actually
// reads via getSourceDb(). This is the read contract between the indexer (which
// owns the write schema) and the API (which reads it raw). A column rename or
// removal on the producer side that isn't reflected here is caught by the
// snapshot drift test; the `satisfies` clause guarantees every entry is a real
// table + column today.
//
// Computed/aliased read expressions are intentionally excluded — they are not
// part of the producer contract: `cursor`/`block_time` where derived in SQL
// rather than stored, window ranks (stream_event_index), and JSONB extractions
// from `events.data`. Generated bookkeeping columns (created_at/updated_at) are
// excluded unless a read path selects them.
export const SOURCE_READ_COLUMNS = {
	blocks: [
		"burn_block_hash",
		"burn_block_height",
		"canonical",
		"hash",
		"height",
		"parent_hash",
		"timestamp",
	],
	decoded_events: [
		"amount",
		"asset_identifier",
		"block_height",
		"canonical",
		"contract_id",
		"cursor",
		"event_index",
		"event_type",
		"memo",
		"payload",
		"recipient",
		"sender",
		"tx_id",
		"tx_index",
		"value",
	],
	transactions: [
		"block_height",
		"contract_id",
		"function_args",
		"function_name",
		"raw_result",
		"raw_tx",
		"sender",
		"status",
		"tx_id",
		"tx_index",
		"type",
	],
	mempool_transactions: [
		"contract_id",
		"function_args",
		"function_name",
		"raw_tx",
		"received_at",
		"sender",
		"seq",
		"tx_id",
		"type",
	],
	pox4_calls: [
		"aggregated_amount_ustx",
		"aggregated_signer_index",
		"amount_ustx",
		"auth_allowed",
		"auth_id",
		"auth_period",
		"auth_topic",
		"block_height",
		"block_time",
		"burn_block_height",
		"caller",
		"canonical",
		"cursor",
		"delegate_to",
		"end_cycle",
		"function_name",
		"lock_period",
		"max_amount",
		"pox_addr_btc",
		"pox_addr_hashbytes",
		"pox_addr_version",
		"result_ok",
		"reward_cycle",
		"signer_key",
		"signer_signature",
		"source_cursor",
		"stacker",
		"start_cycle",
		"tx_id",
		"tx_index",
	],
	sbtc_events: [
		"amount",
		"bitcoin_txid",
		"block_height",
		"block_time",
		"burn_hash",
		"burn_height",
		"canonical",
		"cursor",
		"event_index",
		"fee",
		"governance_contract_type",
		"governance_new_contract",
		"max_fee",
		"output_index",
		"recipient_btc_hashbytes",
		"recipient_btc_version",
		"request_id",
		"sender",
		"signer_address",
		"signer_aggregate_pubkey",
		"signer_bitmap",
		"signer_keys_count",
		"signer_threshold",
		"sweep_txid",
		"topic",
		"tx_id",
		"tx_index",
	],
	sbtc_token_events: [
		"amount",
		"block_height",
		"block_time",
		"canonical",
		"cursor",
		"event_index",
		"event_type",
		"memo",
		"recipient",
		"sender",
		"tx_id",
		"tx_index",
	],
	bns_name_events: [
		"block_height",
		"block_time",
		"bns_id",
		"canonical",
		"cursor",
		"event_index",
		"fqn",
		"hashed_salted_fqn_preorder",
		"imported_at",
		"name",
		"namespace",
		"owner",
		"preordered_by",
		"registered_at",
		"renewal_height",
		"stx_burn",
		"topic",
		"tx_id",
		"tx_index",
	],
	bns_namespace_events: [
		"block_height",
		"block_time",
		"canonical",
		"cursor",
		"event_index",
		"launched_at",
		"lifetime",
		"manager",
		"manager_frozen",
		"manager_transfers_disabled",
		"namespace",
		"price_frozen",
		"price_function",
		"revealed_at",
		"status",
		"tx_id",
		"tx_index",
	],
	bns_marketplace_events: [
		"action",
		"block_height",
		"block_time",
		"bns_id",
		"canonical",
		"commission",
		"cursor",
		"event_index",
		"price_ustx",
		"tx_id",
		"tx_index",
	],
	bns_names: [
		"bns_id",
		"fqn",
		"last_event_at",
		"last_event_cursor",
		"name",
		"namespace",
		"owner",
		"registered_at",
		"renewal_height",
	],
	bns_namespaces: [
		"last_event_at",
		"last_event_cursor",
		"launched_at",
		"lifetime",
		"manager",
		"manager_frozen",
		"name_count",
		"namespace",
		"price_frozen",
	],
	burn_block_rewards: [
		"amount_sats",
		"burn_amount",
		"burn_block_hash",
		"burn_block_height",
		"canonical",
		"cursor",
		"recipient_btc",
		"reward_index",
	],
	burn_block_reward_slots: [
		"burn_block_hash",
		"burn_block_height",
		"canonical",
		"cursor",
		"holder_btc",
		"slot_index",
	],
	events: ["block_height", "data", "event_index", "tx_id", "type"],
	chain_reorgs: ["detected_at"],
} as const satisfies {
	readonly [T in keyof Database]?: readonly (keyof Database[T])[];
};

/** Portable column type for the Index read domain (a lean, ORM-agnostic vocab). */
export type IndexColumnType = "text" | "int" | "boolean" | "timestamp" | "jsonb";

export interface IndexColumn {
	type: IndexColumnType;
	/** SELECT type includes `| null`. Omitted = NOT NULL. */
	nullable?: boolean;
}

// The portable TS/SQL type for every column in SOURCE_READ_COLUMNS, single-sourced
// from the `Database` interface (the producer's typed schema). This is what lets
// `sl index codegen` emit a typed ORM/JSON-Schema for the public Index domain so a
// BYO database mirror is fully typed and can't drift from the API. The drift test
// (source-read-columns.test.ts) asserts this covers exactly SOURCE_READ_COLUMNS;
// the `satisfies` clause guarantees a type entry for every read table.
//
// `string` amount/value columns (e.g. amount_ustx, fee, price_ustx) are NUMERIC in
// Postgres surfaced as strings — `text` here is lossless for a read mirror. `number`
// columns map to `int`. Enum string-unions (topic, status, …) map to `text`.
export const SOURCE_READ_TYPES = {
	blocks: {
		burn_block_hash: { type: "text", nullable: true },
		burn_block_height: { type: "int" },
		canonical: { type: "boolean" },
		hash: { type: "text" },
		height: { type: "int" },
		parent_hash: { type: "text" },
		timestamp: { type: "int" },
	},
	decoded_events: {
		amount: { type: "text", nullable: true },
		asset_identifier: { type: "text", nullable: true },
		block_height: { type: "int" },
		canonical: { type: "boolean" },
		contract_id: { type: "text", nullable: true },
		cursor: { type: "text" },
		event_index: { type: "int" },
		event_type: { type: "text" },
		memo: { type: "text", nullable: true },
		payload: { type: "jsonb", nullable: true },
		recipient: { type: "text", nullable: true },
		sender: { type: "text", nullable: true },
		tx_id: { type: "text" },
		tx_index: { type: "int" },
		value: { type: "text", nullable: true },
	},
	transactions: {
		block_height: { type: "int" },
		contract_id: { type: "text", nullable: true },
		function_args: { type: "jsonb", nullable: true },
		function_name: { type: "text", nullable: true },
		raw_result: { type: "text", nullable: true },
		raw_tx: { type: "text" },
		sender: { type: "text" },
		status: { type: "text" },
		tx_id: { type: "text" },
		tx_index: { type: "int" },
		type: { type: "text" },
	},
	mempool_transactions: {
		contract_id: { type: "text", nullable: true },
		function_args: { type: "jsonb", nullable: true },
		function_name: { type: "text", nullable: true },
		raw_tx: { type: "text" },
		received_at: { type: "timestamp" },
		sender: { type: "text" },
		seq: { type: "text" },
		tx_id: { type: "text" },
		type: { type: "text" },
	},
	pox4_calls: {
		aggregated_amount_ustx: { type: "text", nullable: true },
		aggregated_signer_index: { type: "int", nullable: true },
		amount_ustx: { type: "text", nullable: true },
		auth_allowed: { type: "boolean", nullable: true },
		auth_id: { type: "text", nullable: true },
		auth_period: { type: "int", nullable: true },
		auth_topic: { type: "text", nullable: true },
		block_height: { type: "int" },
		block_time: { type: "timestamp" },
		burn_block_height: { type: "int" },
		caller: { type: "text" },
		canonical: { type: "boolean" },
		cursor: { type: "text" },
		delegate_to: { type: "text", nullable: true },
		end_cycle: { type: "int", nullable: true },
		function_name: { type: "text" },
		lock_period: { type: "int", nullable: true },
		max_amount: { type: "text", nullable: true },
		pox_addr_btc: { type: "text", nullable: true },
		pox_addr_hashbytes: { type: "text", nullable: true },
		pox_addr_version: { type: "int", nullable: true },
		result_ok: { type: "boolean" },
		reward_cycle: { type: "int", nullable: true },
		signer_key: { type: "text", nullable: true },
		signer_signature: { type: "text", nullable: true },
		source_cursor: { type: "text" },
		stacker: { type: "text", nullable: true },
		start_cycle: { type: "int", nullable: true },
		tx_id: { type: "text" },
		tx_index: { type: "int" },
	},
	sbtc_events: {
		amount: { type: "text", nullable: true },
		bitcoin_txid: { type: "text", nullable: true },
		block_height: { type: "int" },
		block_time: { type: "timestamp" },
		burn_hash: { type: "text", nullable: true },
		burn_height: { type: "int", nullable: true },
		canonical: { type: "boolean" },
		cursor: { type: "text" },
		event_index: { type: "int" },
		fee: { type: "text", nullable: true },
		governance_contract_type: { type: "int", nullable: true },
		governance_new_contract: { type: "text", nullable: true },
		max_fee: { type: "text", nullable: true },
		output_index: { type: "int", nullable: true },
		recipient_btc_hashbytes: { type: "text", nullable: true },
		recipient_btc_version: { type: "int", nullable: true },
		request_id: { type: "int", nullable: true },
		sender: { type: "text", nullable: true },
		signer_address: { type: "text", nullable: true },
		signer_aggregate_pubkey: { type: "text", nullable: true },
		signer_bitmap: { type: "text", nullable: true },
		signer_keys_count: { type: "int", nullable: true },
		signer_threshold: { type: "int", nullable: true },
		sweep_txid: { type: "text", nullable: true },
		topic: { type: "text" },
		tx_id: { type: "text" },
		tx_index: { type: "int" },
	},
	sbtc_token_events: {
		amount: { type: "text" },
		block_height: { type: "int" },
		block_time: { type: "timestamp" },
		canonical: { type: "boolean" },
		cursor: { type: "text" },
		event_index: { type: "int" },
		event_type: { type: "text" },
		memo: { type: "text", nullable: true },
		recipient: { type: "text", nullable: true },
		sender: { type: "text", nullable: true },
		tx_id: { type: "text" },
		tx_index: { type: "int" },
	},
	bns_name_events: {
		block_height: { type: "int" },
		block_time: { type: "timestamp" },
		bns_id: { type: "text" },
		canonical: { type: "boolean" },
		cursor: { type: "text" },
		event_index: { type: "int" },
		fqn: { type: "text" },
		hashed_salted_fqn_preorder: { type: "text", nullable: true },
		imported_at: { type: "int", nullable: true },
		name: { type: "text" },
		namespace: { type: "text" },
		owner: { type: "text", nullable: true },
		preordered_by: { type: "text", nullable: true },
		registered_at: { type: "int", nullable: true },
		renewal_height: { type: "int", nullable: true },
		stx_burn: { type: "text", nullable: true },
		topic: { type: "text" },
		tx_id: { type: "text" },
		tx_index: { type: "int" },
	},
	bns_namespace_events: {
		block_height: { type: "int" },
		block_time: { type: "timestamp" },
		canonical: { type: "boolean" },
		cursor: { type: "text" },
		event_index: { type: "int" },
		launched_at: { type: "int", nullable: true },
		lifetime: { type: "int", nullable: true },
		manager: { type: "text", nullable: true },
		manager_frozen: { type: "boolean", nullable: true },
		manager_transfers_disabled: { type: "boolean", nullable: true },
		namespace: { type: "text" },
		price_frozen: { type: "boolean", nullable: true },
		price_function: { type: "text", nullable: true },
		revealed_at: { type: "int", nullable: true },
		status: { type: "text" },
		tx_id: { type: "text" },
		tx_index: { type: "int" },
	},
	bns_marketplace_events: {
		action: { type: "text" },
		block_height: { type: "int" },
		block_time: { type: "timestamp" },
		bns_id: { type: "text" },
		canonical: { type: "boolean" },
		commission: { type: "text", nullable: true },
		cursor: { type: "text" },
		event_index: { type: "int" },
		price_ustx: { type: "text", nullable: true },
		tx_id: { type: "text" },
		tx_index: { type: "int" },
	},
	bns_names: {
		bns_id: { type: "text" },
		fqn: { type: "text" },
		last_event_at: { type: "timestamp" },
		last_event_cursor: { type: "text" },
		name: { type: "text" },
		namespace: { type: "text" },
		owner: { type: "text" },
		registered_at: { type: "int", nullable: true },
		renewal_height: { type: "int", nullable: true },
	},
	bns_namespaces: {
		last_event_at: { type: "timestamp" },
		last_event_cursor: { type: "text" },
		launched_at: { type: "int", nullable: true },
		lifetime: { type: "int", nullable: true },
		manager: { type: "text", nullable: true },
		manager_frozen: { type: "boolean" },
		name_count: { type: "int" },
		namespace: { type: "text" },
		price_frozen: { type: "boolean" },
	},
	burn_block_rewards: {
		amount_sats: { type: "text" },
		burn_amount: { type: "text" },
		burn_block_hash: { type: "text" },
		burn_block_height: { type: "int" },
		canonical: { type: "boolean" },
		cursor: { type: "text" },
		recipient_btc: { type: "text" },
		reward_index: { type: "int" },
	},
	burn_block_reward_slots: {
		burn_block_hash: { type: "text" },
		burn_block_height: { type: "int" },
		canonical: { type: "boolean" },
		cursor: { type: "text" },
		holder_btc: { type: "text" },
		slot_index: { type: "int" },
	},
	events: {
		block_height: { type: "int" },
		data: { type: "jsonb" },
		event_index: { type: "int" },
		tx_id: { type: "text" },
		type: { type: "text" },
	},
	chain_reorgs: {
		detected_at: { type: "timestamp" },
	},
} as const satisfies Record<
	keyof typeof SOURCE_READ_COLUMNS,
	Record<string, IndexColumn>
>;
