import type { Database } from "./types.ts";

// The physical source-table columns the public read API (packages/api) actually
// reads via getSourceDb(). This is the read contract between the indexer (which
// owns the write schema) and the API (which reads it raw). A column rename or
// removal on the producer side that isn't reflected here is caught by the
// snapshot drift test; the `satisfies` clause guarantees every entry is a real
// table + column today.
//
// Computed/aliased read expressions are intentionally excluded — they are not
// part of the producer contract: `cursor`/`block_time` where derived in SQL
// rather than stored, window ranks (stream_event_index), and JSONB extractions
// from `events.data`. Generated bookkeeping columns (created_at/updated_at) are
// excluded unless a read path selects them.
export const SOURCE_READ_COLUMNS = {
	blocks: [
		"burn_block_hash",
		"burn_block_height",
		"canonical",
		"hash",
		"height",
		"parent_hash",
		"timestamp",
	],
	decoded_events: [
		"amount",
		"asset_identifier",
		"block_height",
		"canonical",
		"contract_id",
		"cursor",
		"event_index",
		"event_type",
		"memo",
		"payload",
		"recipient",
		"sender",
		"tx_id",
		"tx_index",
		"value",
	],
	transactions: [
		"block_height",
		"contract_id",
		"function_args",
		"function_name",
		"raw_result",
		"raw_tx",
		"sender",
		"status",
		"tx_id",
		"tx_index",
		"type",
	],
	mempool_transactions: [
		"contract_id",
		"function_args",
		"function_name",
		"raw_tx",
		"received_at",
		"sender",
		"seq",
		"tx_id",
		"type",
	],
	pox4_calls: [
		"aggregated_amount_ustx",
		"aggregated_signer_index",
		"amount_ustx",
		"auth_allowed",
		"auth_id",
		"auth_period",
		"auth_topic",
		"block_height",
		"block_time",
		"burn_block_height",
		"caller",
		"canonical",
		"cursor",
		"delegate_to",
		"end_cycle",
		"function_name",
		"lock_period",
		"max_amount",
		"pox_addr_btc",
		"pox_addr_hashbytes",
		"pox_addr_version",
		"result_ok",
		"reward_cycle",
		"signer_key",
		"signer_signature",
		"source_cursor",
		"stacker",
		"start_cycle",
		"tx_id",
		"tx_index",
	],
	sbtc_events: [
		"amount",
		"bitcoin_txid",
		"block_height",
		"block_time",
		"burn_hash",
		"burn_height",
		"canonical",
		"cursor",
		"event_index",
		"fee",
		"governance_contract_type",
		"governance_new_contract",
		"max_fee",
		"output_index",
		"recipient_btc_hashbytes",
		"recipient_btc_version",
		"request_id",
		"sender",
		"signer_address",
		"signer_aggregate_pubkey",
		"signer_bitmap",
		"signer_keys_count",
		"signer_threshold",
		"sweep_txid",
		"topic",
		"tx_id",
		"tx_index",
	],
	sbtc_token_events: [
		"amount",
		"block_height",
		"block_time",
		"canonical",
		"cursor",
		"event_index",
		"event_type",
		"memo",
		"recipient",
		"sender",
		"tx_id",
		"tx_index",
	],
	bns_name_events: [
		"block_height",
		"block_time",
		"bns_id",
		"canonical",
		"cursor",
		"event_index",
		"fqn",
		"hashed_salted_fqn_preorder",
		"imported_at",
		"name",
		"namespace",
		"owner",
		"preordered_by",
		"registered_at",
		"renewal_height",
		"stx_burn",
		"topic",
		"tx_id",
		"tx_index",
	],
	bns_namespace_events: [
		"block_height",
		"block_time",
		"canonical",
		"cursor",
		"event_index",
		"launched_at",
		"lifetime",
		"manager",
		"manager_frozen",
		"manager_transfers_disabled",
		"namespace",
		"price_frozen",
		"price_function",
		"revealed_at",
		"status",
		"tx_id",
		"tx_index",
	],
	bns_marketplace_events: [
		"action",
		"block_height",
		"block_time",
		"bns_id",
		"canonical",
		"commission",
		"cursor",
		"event_index",
		"price_ustx",
		"tx_id",
		"tx_index",
	],
	bns_names: [
		"bns_id",
		"fqn",
		"last_event_at",
		"last_event_cursor",
		"name",
		"namespace",
		"owner",
		"registered_at",
		"renewal_height",
	],
	bns_namespaces: [
		"last_event_at",
		"last_event_cursor",
		"launched_at",
		"lifetime",
		"manager",
		"manager_frozen",
		"name_count",
		"namespace",
		"price_frozen",
	],
	burn_block_rewards: [
		"amount_sats",
		"burn_amount",
		"burn_block_hash",
		"burn_block_height",
		"canonical",
		"cursor",
		"recipient_btc",
		"reward_index",
	],
	burn_block_reward_slots: [
		"burn_block_hash",
		"burn_block_height",
		"canonical",
		"cursor",
		"holder_btc",
		"slot_index",
	],
	events: ["block_height", "data", "event_index", "tx_id", "type"],
	chain_reorgs: ["detected_at"],
} as const satisfies {
	readonly [T in keyof Database]?: readonly (keyof Database[T])[];
};
