import { type DefineConfigItem, defineConfig } from "bunup";

const config: DefineConfigItem = defineConfig({
	splitting: false,
	entry: [
		"src/index.ts",
		"src/db/index.ts",
		"src/db/queries/integrity.ts",
		"src/db/queries/accounts.ts",
		"src/db/queries/usage.ts",
		"src/db/queries/subgraphs.ts",
		"src/db/queries/subgraph-gaps.ts",
		"src/db/queries/subgraph-operations.ts",
		"src/db/queries/projects.ts",
		"src/db/queries/provisioning-audit.ts",
		"src/db/queries/tenant-compute-addons.ts",
		"src/db/queries/account-spend-caps.ts",
		"src/db/jsonb.ts",
		"src/db/schema.ts",
		"src/queue/listener.ts",
		"src/schemas/index.ts",
		"src/schemas/accounts.ts",
		"src/schemas/filters.ts",
		"src/schemas/subgraphs.ts",
		"src/schemas/subscriptions.ts",
		"src/db/queries/account-usage.ts",
		"src/db/queries/subscriptions.ts",
		"src/db/queries/tenants.ts",
		"src/types.ts",
		"src/env.ts",
		"src/mode.ts",
		"src/logger.ts",
		"src/errors.ts",
		"src/constants.ts",
		"src/crypto/hmac.ts",
		"src/crypto/secrets.ts",
		"src/crypto/standard-webhooks.ts",
		"src/pricing.ts",
		"src/node/client.ts",
		"src/node/hiro-client.ts",
		"src/node/local-client.ts",
		"src/node/hiro-pg-client.ts",
		"src/node/archive-client.ts",
	],
	format: ["esm"],
	dts: true,
	sourcemap: "linked",
	minify: false,
	external: ["kysely", "kysely-postgres-js", "postgres", "zod"],
}) as DefineConfigItem;
export default config;
