import { defineConfig, type DefineConfigItem } from "bunup";

const config: DefineConfigItem = defineConfig({
  splitting: false,
  entry: [
    "src/index.ts",
    "src/db/index.ts",
    "src/db/queries/integrity.ts",
    "src/db/queries/metrics.ts",
    "src/db/queries/accounts.ts",
    "src/db/queries/usage.ts",
    "src/db/queries/subgraphs.ts",
    "src/db/jsonb.ts",
    "src/db/schema.ts",
    "src/lib/plans.ts",
    "src/queue/index.ts",
    "src/queue/listener.ts",
    "src/queue/recovery.ts",
    "src/schemas/index.ts",
    "src/schemas/filters.ts",
    "src/schemas/subgraphs.ts",
    "src/types.ts",
    "src/env.ts",
    "src/logger.ts",
    "src/errors.ts",
    "src/crypto/hmac.ts",
    "src/node/client.ts",
    "src/node/hiro-client.ts",
    "src/node/local-client.ts",
  ],
  format: ["esm"],
  dts: true,
  sourcemap: "linked",
  minify: false,
  external: ["kysely", "kysely-postgres-js", "postgres", "zod"],
}) as DefineConfigItem;
export default config;
