import { type DefineConfigItem, defineConfig } from "bunup";

const config: DefineConfigItem[] = defineConfig([
	{
		name: "stacks",
		entry: [
			"src/index.ts",
			"src/accounts/index.ts",
			"src/chains/index.ts",
			"src/clarity/index.ts",
			"src/actions/index.ts",
			"src/postconditions/index.ts",
			"src/transactions/index.ts",
			"src/utils/index.ts",
			"src/bns/index.ts",
			"src/pox/index.ts",
			"src/stackingdao/index.ts",
			"src/subscriptions/index.ts",
		],
		format: ["esm", "cjs"],
		dts: true,
		splitting: true,
		sourcemap: "linked",
		minify: false,
	},
	{
		name: "connect",
		entry: ["src/connect/index.ts"],
		outDir: "dist/src/connect",
		format: ["esm", "cjs"],
		dts: true,
		target: "browser",
		splitting: false,
		sourcemap: "linked",
		minify: false,
	},
	{
		name: "walletconnect",
		entry: ["src/connect/walletconnect/index.ts"],
		outDir: "dist/src/connect/walletconnect",
		format: ["esm", "cjs"],
		dts: true,
		target: "browser",
		splitting: false,
		sourcemap: "linked",
		minify: false,
	},
	{
		name: "ui",
		entry: ["src/ui/index.ts"],
		outDir: "dist/src/ui",
		format: ["esm", "cjs"],
		dts: true,
		target: "browser",
		splitting: false,
		sourcemap: "linked",
		minify: false,
		external: [
			"react",
			"react/jsx-runtime",
			"@json-render/core",
			"@json-render/react",
			"zod",
		],
	},
	{
		name: "ui-schemas",
		entry: ["src/ui/schemas.ts"],
		outDir: "dist/src/ui",
		format: ["esm", "cjs"],
		dts: true,
		// Pure Zod, no React — safe to bundle as neutral.
		splitting: false,
		sourcemap: "linked",
		minify: false,
		external: ["zod"],
	},
	{
		name: "tools",
		entry: ["src/tools/index.ts"],
		outDir: "dist/src/tools",
		format: ["esm", "cjs"],
		dts: true,
		splitting: false,
		sourcemap: "linked",
		minify: false,
		external: ["ai", "zod", "@stacks/transactions"],
	},
	{
		name: "tools-btc",
		entry: ["src/tools/btc/index.ts"],
		outDir: "dist/src/tools/btc",
		format: ["esm", "cjs"],
		dts: true,
		splitting: false,
		sourcemap: "linked",
		minify: false,
		external: ["ai", "zod"],
	},
	{
		name: "triggers",
		entry: ["src/triggers/index.ts"],
		outDir: "dist/src/triggers",
		format: ["esm", "cjs"],
		dts: true,
		splitting: false,
		sourcemap: "linked",
		minify: false,
		external: ["@secondlayer/subgraphs"],
	},
	{
		name: "tx",
		entry: ["src/tx/index.ts"],
		outDir: "dist/src/tx",
		format: ["esm", "cjs"],
		dts: true,
		splitting: false,
		sourcemap: "linked",
		minify: false,
		external: ["@stacks/transactions"],
	},
]) as DefineConfigItem[];
export default config;
