import { defineConfig } from "bunup";

export default defineConfig([
  {
    name: "stacks",
    entry: [
      "src/index.ts",
      "src/accounts/index.ts",
      "src/chains/index.ts",
      "src/clarity/index.ts",
      "src/actions/index.ts",
      "src/postconditions/index.ts",
      "src/transactions/index.ts",
      "src/utils/index.ts",
      "src/bns/index.ts",
      "src/pox/index.ts",
      "src/stackingdao/index.ts",
      "src/subscriptions/index.ts",
    ],
    format: ["esm", "cjs"],
    dts: true,
    splitting: true,
    sourcemap: "linked",
    minify: false,
  },
  {
    name: "connect",
    entry: ["src/connect/index.ts"],
    outDir: "dist/src/connect",
    format: ["esm", "cjs"],
    dts: true,
    target: "browser",
    splitting: false,
    sourcemap: "linked",
    minify: false,
  },
  {
    name: "walletconnect",
    entry: ["src/connect/walletconnect/index.ts"],
    outDir: "dist/src/connect/walletconnect",
    format: ["esm", "cjs"],
    dts: true,
    target: "browser",
    splitting: false,
    sourcemap: "linked",
    minify: false,
  },
]);
