import {
	type IndexColumn,
	type IndexColumnType,
	SOURCE_READ_TYPES,
} from "@secondlayer/shared/db";

/**
 * Emit a portable, typed schema for the public Index read domain (blocks,
 * decoded events, transactions, stacking, sBTC, BNS, …) from the single-sourced
 * `SOURCE_READ_TYPES` registry. This is the Index arm of the "typed Stacks data in
 * your own stack" story: a BYO-database consumer mirrors Index rows and gets a
 * fully-typed ORM / JSON-Schema that can't drift from the API (the registry is
 * drift-tested against the producer's read contract).
 *
 * Prisma is intentionally unsupported here — its models require an `@id`, and the
 * read registry carries no primary-key metadata. Kysely/Drizzle/JSON-Schema model
 * read mirrors without a declared PK.
 */

export type IndexCodegenTarget = "kysely" | "drizzle" | "json-schema";

export interface IndexCodegenOptions {
	/** Restrict output to these Index tables (default: all). */
	tables?: string[];
	/** Postgres schema to qualify table names with (default: bare names). */
	schemaName?: string;
}

type IndexTables = typeof SOURCE_READ_TYPES;

function pascalCase(name: string): string {
	return name
		.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase())
		.replace(/^[a-z]/, (c) => c.toUpperCase());
}

function snakeToCamel(name: string): string {
	return name.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

/** Resolve the requested tables (validated) → ordered [table, columns] entries. */
function selectTables(
	opts: IndexCodegenOptions,
): Array<[string, Record<string, IndexColumn>]> {
	const all = SOURCE_READ_TYPES as Record<string, Record<string, IndexColumn>>;
	const names = opts.tables ?? Object.keys(all);
	return names.map((name) => {
		const cols = all[name];
		if (!cols) {
			throw new Error(
				`Unknown Index table "${name}". Known: ${Object.keys(all).sort().join(", ")}`,
			);
		}
		return [name, cols];
	});
}

const KYSELY_TYPE: Record<IndexColumnType, string> = {
	text: "string",
	int: "number",
	boolean: "boolean",
	timestamp: "Date",
	jsonb: "unknown",
};

function generateKysely(
	entries: Array<[string, Record<string, IndexColumn>]>,
	schemaName?: string,
): string {
	const interfaces = entries.map(([table, cols]) => {
		const lines = Object.entries(cols).map(([col, def]) => {
			const type = def.nullable
				? `${KYSELY_TYPE[def.type]} | null`
				: KYSELY_TYPE[def.type];
			return `  ${col}: ${type};`;
		});
		return `export interface ${pascalCase(table)} {\n${lines.join("\n")}\n}`;
	});
	const dbEntries = entries.map(([table]) => {
		const key = schemaName ? `${schemaName}.${table}` : table;
		return `  "${key}": ${pascalCase(table)};`;
	});
	const rows = entries.map(
		([table]) =>
			`export type ${pascalCase(table)}Row = Selectable<${pascalCase(table)}>;`,
	);
	return [
		"// Generated by `sl index codegen --target kysely`. Do not edit by hand.",
		`import type { Selectable } from "kysely";`,
		"",
		interfaces.join("\n\n"),
		"",
		`export interface IndexDB {\n${dbEntries.join("\n")}\n}`,
		"",
		rows.join("\n"),
		"",
	].join("\n");
}

const DRIZZLE_BUILDER: Record<IndexColumnType, (col: string) => string> = {
	text: (c) => `text("${c}")`,
	int: (c) => `integer("${c}")`,
	boolean: (c) => `boolean("${c}")`,
	timestamp: (c) => `timestamp("${c}", { withTimezone: true })`,
	jsonb: (c) => `jsonb("${c}")`,
};

const DRIZZLE_BUILDER_NAME: Record<IndexColumnType, string> = {
	text: "text",
	int: "integer",
	boolean: "boolean",
	timestamp: "timestamp",
	jsonb: "jsonb",
};

function generateDrizzle(
	entries: Array<[string, Record<string, IndexColumn>]>,
	schemaName?: string,
): string {
	const used = new Set<string>();
	for (const [, cols] of entries)
		for (const def of Object.values(cols))
			used.add(DRIZZLE_BUILDER_NAME[def.type]);
	if (schemaName) used.add("pgSchema");
	else used.add("pgTable");

	const tableFn = schemaName ? "sg.table" : "pgTable";
	const tables = entries.map(([table, cols]) => {
		const lines = Object.entries(cols).map(([col, def]) => {
			let line = `  ${snakeToCamel(col)}: ${DRIZZLE_BUILDER[def.type](col)}`;
			if (!def.nullable) line += ".notNull()";
			return `${line},`;
		});
		return `export const ${snakeToCamel(table)} = ${tableFn}("${table}", {\n${lines.join("\n")}\n});`;
	});
	const rows = entries.map(
		([table]) =>
			`export type ${pascalCase(table)} = typeof ${snakeToCamel(table)}.$inferSelect;`,
	);
	return [
		"// Generated by `sl index codegen --target drizzle`. Do not edit by hand.",
		`import { ${[...used].sort().join(", ")} } from "drizzle-orm/pg-core";`,
		"",
		...(schemaName ? [`export const sg = pgSchema("${schemaName}");`, ""] : []),
		tables.join("\n\n"),
		"",
		rows.join("\n"),
		"",
	].join("\n");
}

const JSON_SCHEMA_TYPE: Record<IndexColumnType, Record<string, unknown>> = {
	text: { type: "string" },
	int: { type: "integer" },
	boolean: { type: "boolean" },
	timestamp: { type: "string", format: "date-time" },
	jsonb: {},
};

function generateJsonSchema(
	entries: Array<[string, Record<string, IndexColumn>]>,
): string {
	const defs: Record<string, unknown> = {};
	for (const [table, cols] of entries) {
		const properties: Record<string, unknown> = {};
		const required: string[] = [];
		for (const [col, def] of Object.entries(cols)) {
			const base = JSON_SCHEMA_TYPE[def.type];
			if (def.nullable && "type" in base) {
				properties[col] = { ...base, type: [base.type, "null"] };
			} else {
				properties[col] = { ...base };
				if (!def.nullable) required.push(col);
			}
		}
		defs[pascalCase(table)] = {
			type: "object",
			properties,
			required,
			additionalProperties: false,
		};
	}
	return `${JSON.stringify(
		{
			$schema: "https://json-schema.org/draft/2020-12/schema",
			title: "Secondlayer Index domain",
			$defs: defs,
		},
		null,
		2,
	)}\n`;
}

export function generateIndexSchema(
	target: IndexCodegenTarget,
	opts: IndexCodegenOptions = {},
): string {
	const entries = selectTables(opts);
	switch (target) {
		case "kysely":
			return generateKysely(entries, opts.schemaName);
		case "drizzle":
			return generateDrizzle(entries, opts.schemaName);
		case "json-schema":
			return generateJsonSchema(entries);
		default:
			throw new Error(`Unsupported Index codegen target "${target}".`);
	}
}

/** Index tables available to codegen, for help text and validation. */
export const INDEX_CODEGEN_TABLES: readonly string[] = Object.keys(
	SOURCE_READ_TYPES,
) as Array<keyof IndexTables>;
