import type {
	ColumnType,
	SubgraphDefinition,
	SubgraphTable,
} from "../types.ts";
import { pgSchemaName } from "./utils.ts";

/**
 * Generate Kysely table interfaces from a subgraph definition — the Kysely arm of
 * the "Prisma wrapper for Stacks" story (alongside prisma.ts/drizzle.ts). Emits a
 * per-table interface plus a `DB` registry keyed by schema-qualified table name,
 * so `new Kysely<DB>()` gives fully-typed query building over BYO decoded rows.
 * Output mirrors the deployed DDL in generator.ts — tables are processor-written,
 * so treat them read-only. Column keys stay as the real DB names (Kysely maps to
 * physical columns, unlike the camel-cased Prisma/Drizzle models).
 */

/** Subgraph column type → Kysely TS type. numeric/bigint serialize as string (lossless for Clarity uint128/int128). */
const KYSELY_TYPE: Record<ColumnType, string> = {
	uint: "string",
	int: "string",
	text: "string",
	principal: "string",
	boolean: "boolean",
	timestamp: "Date",
	jsonb: "unknown",
};

/** System columns every subgraph table gets (kept in sync with generator.ts). */
const SYSTEM_FIELDS: Array<{ col: string; type: string }> = [
	{ col: "_id", type: "Generated<string>" },
	{ col: "_block_height", type: "string" },
	{ col: "_tx_id", type: "string" },
	{ col: "_created_at", type: "Generated<Date>" },
];

function pascalCase(name: string): string {
	return name
		.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase())
		.replace(/^[a-z]/, (c) => c.toUpperCase());
}

function renderTable(tableName: string, table: SubgraphTable): string {
	const lines = SYSTEM_FIELDS.map((f) => `  ${f.col}: ${f.type};`);
	for (const [colName, col] of Object.entries(table.columns)) {
		let type = KYSELY_TYPE[col.type];
		if (col.nullable) type = `${type} | null`;
		// A DB-side default makes the column optional on insert — Generated<> models that.
		if (col.default !== undefined) type = `Generated<${type}>`;
		lines.push(`  ${colName}: ${type};`);
	}
	return `export interface ${pascalCase(tableName)} {\n${lines.join("\n")}\n}`;
}

export interface KyselyGenOptions {
	/** Postgres schema the tables live in (account-scoped). */
	schemaName?: string;
}

export function generateKyselySchema(
	def: SubgraphDefinition,
	opts: KyselyGenOptions = {},
): string {
	const schemaName = opts.schemaName ?? pgSchemaName(def.name);

	const interfaces = Object.entries(def.schema).map(([name, table]) =>
		renderTable(name, table),
	);

	// DB registry — schema-qualified keys so `db.selectFrom("schema.table")` resolves.
	const dbEntries = Object.keys(def.schema).map(
		(name) => `  "${schemaName}.${name}": ${pascalCase(name)};`,
	);
	const dbRegistry = `export interface DB {\n${dbEntries.join("\n")}\n}`;

	// Selectable row aliases for ergonomic typed reads.
	const rowExports = Object.keys(def.schema).map(
		(name) => `export type ${pascalCase(name)}Row = Selectable<${pascalCase(name)}>;`,
	);

	return [
		`// Generated by \`sl subgraphs codegen --target kysely\` from subgraph "${def.name}". Do not edit by hand.`,
		`import type { Generated, Selectable } from "kysely";`,
		"",
		interfaces.join("\n\n"),
		"",
		dbRegistry,
		"",
		rowExports.join("\n"),
		"",
	].join("\n");
}
