/**
 * Generates a self-contained docker-compose for the Secondlayer app services
 * (postgres + migrate + api + indexer + subgraph-processor), pinned to the
 * published OSS images so a CLI-only developer — with no repo checkout — can
 * run the stack alongside their own `clarinet devnet`.
 *
 * It mirrors `docker/oss/docker-compose.yml`, with two devnet-specific changes:
 *   - the indexer's Hiro-mainnet fallbacks are disabled (it's fed by the devnet
 *     node's event observer, and any "gap" would otherwise pull mainnet blocks);
 *   - the indexer port publishes on all interfaces so the devnet's stacks-node
 *     container can reach it via `host.docker.internal:3700`.
 *
 * The API is published on loopback only, and told so via `API_PUBLISH_ADDR`,
 * so `/v1` reads on a devnet need no credential — the "no keys" the docs
 * promise. See `apiPublish` below.
 */

/** ghcr namespace the OSS images publish under (oss-images.yml). */
export const DEFAULT_IMAGE_OWNER = "ryanwaits";
export const DEFAULT_IMAGE_TAG = "latest";

/**
 * Local-dev instance token — not a production secret.
 *
 * It has to be here: the api container listens on 0.0.0.0 (nothing published
 * can reach it otherwise) and the boot guard reads the *listen* host, so a
 * tokenless container refuses to start. It is not what gates reads — the API
 * is published on loopback, so `/v1` is keyless — it is the credential every
 * write (`/api/subgraphs`, `/api/subscriptions`, `/api/node`) must send. The
 * compose file and the "next steps" hint share this value so they can't drift.
 */
export const DEV_INSTANCE_TOKEN = "dev-instance-token";

export interface DevnetComposeOptions {
	owner?: string;
	imageTag?: string;
	apiPort?: number;
	indexerPort?: number;
}

export function buildDevnetCompose(opts: DevnetComposeOptions = {}): string {
	const owner = opts.owner ?? DEFAULT_IMAGE_OWNER;
	const tag = opts.imageTag ?? DEFAULT_IMAGE_TAG;
	const apiPort = opts.apiPort ?? 3800;
	const indexerPort = opts.indexerPort ?? 3700;

	// The one publish spec for the api, used verbatim by both `ports:` and
	// `API_PUBLISH_ADDR` so the two can never disagree — same trick
	// `docker/oss/docker-compose.yml` plays with `${API_PORT}`. In a container
	// the listen host cannot say who may reach the API (it must be 0.0.0.0 or
	// the published port never arrives), so the publish spec is the answer the
	// read plane consults. Loopback here → keyless `/v1` reads on devnet.
	const apiPublish = `127.0.0.1:${apiPort}`;

	const apiImage = `ghcr.io/${owner}/secondlayer-api:${tag}`;
	const indexerImage = `ghcr.io/${owner}/secondlayer-indexer:${tag}`;
	const dbUrl = "postgres://secondlayer:secondlayer@postgres:5432/secondlayer";
	// Fixed local-dev secrets key (32 bytes hex), shared by api + subgraph-processor
	// so encrypt-at-rest secrets round-trip across services. Not a production secret.
	const DEV_SECRETS_KEY =
		"deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef";

	// Written verbatim — keep it readable; docker compose parses indentation.
	return `# Generated by \`secondlayer devnet connect\` — do not edit by hand.
# Secondlayer app services for local clarinet devnet development.
name: secondlayer-devnet

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: secondlayer
      POSTGRES_PASSWORD: secondlayer
      POSTGRES_DB: secondlayer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U secondlayer"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  migrate:
    image: ${apiImage}
    command: ["bun", "run", "packages/shared/src/db/migrate.ts"]
    environment:
      DATABASE_URL: ${dbUrl}
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  api:
    image: ${apiImage}
    environment:
      INSTANCE_MODE: oss
      DATABASE_URL: ${dbUrl}
      PORT: 3800
      # 0.0.0.0 is forced: a container process that binds loopback is
      # unreachable through a published port. The real reach is the publish
      # spec below, handed over verbatim so /v1 reads stay keyless on devnet.
      LISTEN_HOST: "0.0.0.0"
      API_PUBLISH_ADDR: "${apiPublish}"
      # Boot guard reads LISTEN_HOST, so a token is required to start at all.
      # It gates writes only — reads are open on this loopback publish.
      INSTANCE_TOKEN: ${DEV_INSTANCE_TOKEN}
      NODE_ENV: production
      DATA_DIR: /data
      # Shared across api + subgraph-processor so the secret the api encrypts
      # (e.g. a subscription's signing secret) can be decrypted by the emitter.
      # OSS auto-generates a per-process key when unset — that splits them.
      # Local-dev fixed value; not a production secret.
      SECONDLAYER_SECRETS_KEY: ${DEV_SECRETS_KEY}
    ports:
      - "${apiPublish}:3800"
    volumes:
      - subgraphs_data:/data/subgraphs
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3800/health"]
      interval: 10s
      timeout: 3s
      start_period: 10s
      retries: 5
    restart: unless-stopped

  indexer:
    image: ${indexerImage}
    environment:
      DATABASE_URL: ${dbUrl}
      PORT: 3700
      NODE_ENV: production
      # Keep every network key aligned: the indexer writes index_progress under
      # STACKS_NETWORK, the subgraph processor reads it under NETWORK. If they
      # differ, catch-up finds no progress row and subgraphs never advance.
      NETWORKS: testnet
      STACKS_NETWORK: testnet
      NETWORK: testnet
      # Fed by the devnet node's event observer — never reach out to Hiro mainnet.
      AUTO_BACKFILL_ENABLED: "false"
      TIP_FOLLOWER_ENABLED: "false"
    # Deliberately published on every interface, unlike the api: the devnet's
    # stacks-node runs in its own container and POSTs events to
    # host.docker.internal:3700, which resolves to the host gateway address,
    # not 127.0.0.1. A loopback publish here would drop every block.
    ports:
      - "${indexerPort}:3700"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3700/health"]
      interval: 10s
      timeout: 3s
      start_period: 10s
      retries: 5
    restart: unless-stopped

  subgraph-processor:
    image: ${apiImage}
    command: ["bun", "run", "packages/subgraphs/src/service.ts"]
    environment:
      DATABASE_URL: ${dbUrl}
      NODE_ENV: production
      DATA_DIR: /data
      # Must match the indexer's network key (see indexer note) — catch-up reads
      # index_progress under NETWORK.
      NETWORK: testnet
      STACKS_NETWORK: testnet
      # The emitter blocks webhook delivery to private/loopback IPs by default.
      # On a local devnet you deliver to your own localhost receiver, so allow it.
      SECONDLAYER_ALLOW_PRIVATE_EGRESS: "true"
      # Must match the api's key so the emitter can decrypt signing secrets.
      SECONDLAYER_SECRETS_KEY: ${DEV_SECRETS_KEY}
    volumes:
      - subgraphs_data:/data/subgraphs
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    healthcheck:
      disable: true
    restart: unless-stopped

volumes:
  postgres_data:
  subgraphs_data:
`;
}
