/**
 * Generates a self-contained docker-compose for the Secondlayer app services
 * (postgres + migrate + api + indexer + subgraph-processor), pinned to the
 * published OSS images so a CLI-only developer — with no repo checkout — can
 * run the stack alongside their own `clarinet devnet`.
 *
 * It mirrors `docker/oss/docker-compose.yml`, with two devnet-specific changes:
 *   - the indexer's Hiro-mainnet fallbacks are disabled (it's fed by the devnet
 *     node's event observer, and any "gap" would otherwise pull mainnet blocks);
 *   - the indexer port binds on all interfaces so the devnet's stacks-node
 *     container can reach it via `host.docker.internal:3700`.
 */

/** ghcr namespace the OSS images publish under (oss-images.yml). */
export const DEFAULT_IMAGE_OWNER = "ryanwaits";
export const DEFAULT_IMAGE_TAG = "latest";

export interface DevnetComposeOptions {
	owner?: string;
	imageTag?: string;
	apiPort?: number;
	indexerPort?: number;
}

export function buildDevnetCompose(opts: DevnetComposeOptions = {}): string {
	const owner = opts.owner ?? DEFAULT_IMAGE_OWNER;
	const tag = opts.imageTag ?? DEFAULT_IMAGE_TAG;
	const apiPort = opts.apiPort ?? 3800;
	const indexerPort = opts.indexerPort ?? 3700;

	const apiImage = `ghcr.io/${owner}/secondlayer-api:${tag}`;
	const indexerImage = `ghcr.io/${owner}/secondlayer-indexer:${tag}`;
	const dbUrl = "postgres://secondlayer:secondlayer@postgres:5432/secondlayer";

	// Written verbatim — keep it readable; docker compose parses indentation.
	return `# Generated by \`sl devnet connect\` — do not edit by hand.
# Secondlayer app services for local clarinet devnet development.
name: secondlayer-devnet

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: secondlayer
      POSTGRES_PASSWORD: secondlayer
      POSTGRES_DB: secondlayer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U secondlayer"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  migrate:
    image: ${apiImage}
    command: ["bun", "run", "packages/shared/src/db/migrate.ts"]
    environment:
      DATABASE_URL: ${dbUrl}
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  api:
    image: ${apiImage}
    environment:
      INSTANCE_MODE: oss
      DATABASE_URL: ${dbUrl}
      PORT: 3800
      NODE_ENV: production
      DATA_DIR: /data
    ports:
      - "${apiPort}:3800"
    volumes:
      - subgraphs_data:/data/subgraphs
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3800/health"]
      interval: 10s
      timeout: 3s
      start_period: 10s
      retries: 5
    restart: unless-stopped

  indexer:
    image: ${indexerImage}
    environment:
      DATABASE_URL: ${dbUrl}
      PORT: 3700
      NODE_ENV: production
      # Keep every network key aligned: the indexer writes index_progress under
      # STACKS_NETWORK, the subgraph processor reads it under NETWORK. If they
      # differ, catch-up finds no progress row and subgraphs never advance.
      NETWORKS: testnet
      STACKS_NETWORK: testnet
      NETWORK: testnet
      # Fed by the devnet node's event observer — never reach out to Hiro mainnet.
      AUTO_BACKFILL_ENABLED: "false"
      TIP_FOLLOWER_ENABLED: "false"
    # Bind on all interfaces so the devnet's stacks-node container can POST to
    # host.docker.internal:3700.
    ports:
      - "${indexerPort}:3700"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3700/health"]
      interval: 10s
      timeout: 3s
      start_period: 10s
      retries: 5
    restart: unless-stopped

  subgraph-processor:
    image: ${apiImage}
    command: ["bun", "run", "packages/subgraphs/src/service.ts"]
    environment:
      DATABASE_URL: ${dbUrl}
      NODE_ENV: production
      DATA_DIR: /data
      # Must match the indexer's network key (see indexer note) — catch-up reads
      # index_progress under NETWORK.
      NETWORK: testnet
      STACKS_NETWORK: testnet
    volumes:
      - subgraphs_data:/data/subgraphs
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    healthcheck:
      disable: true
    restart: unless-stopped

volumes:
  postgres_data:
  subgraphs_data:
`;
}
