import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { ARCHIVE_ROOT_PUBLIC_KEY_PEM } from "@secondlayer/shared/archive/root-key";
import { generateEd25519KeyPair } from "@secondlayer/shared/crypto/ed25519";
import { INSTANCE_NETWORKS } from "@secondlayer/shared/db/queries/instance";
import type { InstanceNetwork } from "@secondlayer/shared/db/queries/instance";
import { printError } from "./output.ts";

export const INSTANCE_ENV_FILE = ".env.local";

export type InstanceEnv = {
	INSTANCE_MODE: "oss";
	STACKS_NETWORK: InstanceNetwork;
	INSTANCE_TOKEN: string;
	SECONDLAYER_SECRETS_KEY: string;
	STREAMS_SIGNING_PRIVATE_KEY: string;
	SECONDLAYER_WEBHOOK_SIGNING_PRIVATE_KEY: string;
	ALLOW_UNSIGNED_WEBHOOKS: "false";
	SL_API_URL: string;
	/** Legacy alias of INSTANCE_TOKEN, written with the same value. Still
	 *  emitted so existing setups that export it keep working; clients prefer
	 *  INSTANCE_TOKEN. */
	SL_API_KEY: string;
	/** The key `bootstrap`, `verify`, and `repair` check archive manifests
	 *  against. Always written, so the instance verifies offline; an existing
	 *  value is kept so an operator's own pin survives re-runs. */
	ARCHIVE_SIGNING_PUBLIC_KEY: string;
};

export function parseInstanceNetwork(value: string): InstanceNetwork {
	const network = value.trim().toLowerCase();
	if ((INSTANCE_NETWORKS as readonly string[]).includes(network)) {
		return network as InstanceNetwork;
	}
	throw new Error(`network must be mainnet, testnet, or devnet (got ${value})`);
}

/**
 * The network a command runs against, from the global `--network` flag (which
 * `cli.ts` funnels into `STACKS_NETWORK`) or the environment. An unknown value
 * is a one-line error and exit 1, not a stack trace: `local` is not a network
 * this CLI knows, and a script that passed it should learn that from the
 * first line of stderr.
 */
export function instanceNetworkFromEnv(fallback = "mainnet"): InstanceNetwork {
	const raw = process.env.STACKS_NETWORK ?? fallback;
	try {
		return parseInstanceNetwork(raw);
	} catch (err) {
		printError(err instanceof Error ? err.message : String(err), {
			hint: "Pass --network mainnet, --network testnet, or --network devnet.",
		});
		process.exit(1);
	}
}

export function generateInstanceToken(): string {
	return randomBytes(32).toString("hex");
}

export function generateSecretsKey(): string {
	return randomBytes(32).toString("hex");
}

export function generateSigningPrivateKey(): string {
	return generateEd25519KeyPair().privateKeyPem;
}

export function escapeEnvValue(value: string): string {
	if (!/[\s#"']/.test(value) && !value.includes("\\")) return value;
	return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
}

export function unescapeEnvValue(raw: string): string {
	let value = raw.trim();
	if (
		(value.startsWith('"') && value.endsWith('"')) ||
		(value.startsWith("'") && value.endsWith("'"))
	) {
		value = value.slice(1, -1);
	}
	return value
		.replace(/\\n/g, "\n")
		.replace(/\\"/g, '"')
		.replace(/\\\\/g, "\\");
}

/** Read a KEY=value from an env file, if present. */
export function readEnvValue(envPath: string, key: string): string | null {
	if (!existsSync(envPath)) return null;
	const match = readFileSync(envPath, "utf8").match(
		new RegExp(`^${key}=(.*)$`, "m"),
	);
	return match ? unescapeEnvValue(match[1]) : null;
}

export function buildInstanceEnv(input: {
	network: InstanceNetwork;
	existing?: Partial<Record<keyof InstanceEnv, string | null>>;
	apiUrl?: string;
	/** Resolved archive key (see `resolveArchivePublicKey`); falls back to the
	 *  key compiled into this release. */
	archivePublicKeyPem?: string;
}): InstanceEnv {
	const token =
		input.existing?.INSTANCE_TOKEN ||
		input.existing?.SL_API_KEY ||
		generateInstanceToken();
	const secrets =
		input.existing?.SECONDLAYER_SECRETS_KEY || generateSecretsKey();
	const signing =
		input.existing?.STREAMS_SIGNING_PRIVATE_KEY ||
		input.existing?.SECONDLAYER_WEBHOOK_SIGNING_PRIVATE_KEY ||
		generateSigningPrivateKey();
	const apiUrl = input.apiUrl ?? "http://127.0.0.1:3800";
	const archiveKey =
		input.existing?.ARCHIVE_SIGNING_PUBLIC_KEY ||
		input.archivePublicKeyPem ||
		ARCHIVE_ROOT_PUBLIC_KEY_PEM;
	return {
		INSTANCE_MODE: "oss",
		STACKS_NETWORK: input.network,
		INSTANCE_TOKEN: token,
		SECONDLAYER_SECRETS_KEY: secrets,
		STREAMS_SIGNING_PRIVATE_KEY: signing,
		SECONDLAYER_WEBHOOK_SIGNING_PRIVATE_KEY: signing,
		ALLOW_UNSIGNED_WEBHOOKS: "false",
		SL_API_URL: input.existing?.SL_API_URL || apiUrl,
		SL_API_KEY: token,
		ARCHIVE_SIGNING_PUBLIC_KEY: archiveKey,
	};
}

export function renderInstanceEnv(env: InstanceEnv): string {
	const lines = [
		"# Generated by secondlayer init. Do not commit.",
		`INSTANCE_MODE=${env.INSTANCE_MODE}`,
		`STACKS_NETWORK=${env.STACKS_NETWORK}`,
		"# The instance credential. The API validates bearer tokens against it,",
		"# and the CLI/SDK/MCP read it first when authenticating.",
		`INSTANCE_TOKEN=${env.INSTANCE_TOKEN}`,
		`SECONDLAYER_SECRETS_KEY=${env.SECONDLAYER_SECRETS_KEY}`,
		`STREAMS_SIGNING_PRIVATE_KEY=${escapeEnvValue(env.STREAMS_SIGNING_PRIVATE_KEY)}`,
		`SECONDLAYER_WEBHOOK_SIGNING_PRIVATE_KEY=${escapeEnvValue(env.SECONDLAYER_WEBHOOK_SIGNING_PRIVATE_KEY)}`,
		`ALLOW_UNSIGNED_WEBHOOKS=${env.ALLOW_UNSIGNED_WEBHOOKS}`,
		`SL_API_URL=${env.SL_API_URL}`,
		"# Legacy alias of INSTANCE_TOKEN, same value. Kept for existing setups;",
		"# INSTANCE_TOKEN wins if the two ever disagree.",
		`SL_API_KEY=${env.SL_API_KEY}`,
	];
	lines.push(
		"# Archive trust root: bootstrap, verify, and repair check manifests",
		"# against this key. Replace it to pin a different archive.",
		`ARCHIVE_SIGNING_PUBLIC_KEY=${escapeEnvValue(env.ARCHIVE_SIGNING_PUBLIC_KEY)}`,
		"",
	);
	return lines.join("\n");
}

export function writeInstanceEnv(
	cwd: string,
	env: InstanceEnv,
	file = INSTANCE_ENV_FILE,
): string {
	const path = resolve(cwd, file);
	writeFileSync(path, renderInstanceEnv(env), { mode: 0o600 });
	return path;
}

export function loadExistingInstanceEnv(
	cwd: string,
	file = INSTANCE_ENV_FILE,
): Partial<Record<keyof InstanceEnv, string | null>> {
	const path = resolve(cwd, file);
	return {
		INSTANCE_TOKEN: readEnvValue(path, "INSTANCE_TOKEN"),
		SECONDLAYER_SECRETS_KEY: readEnvValue(path, "SECONDLAYER_SECRETS_KEY"),
		STREAMS_SIGNING_PRIVATE_KEY: readEnvValue(
			path,
			"STREAMS_SIGNING_PRIVATE_KEY",
		),
		SECONDLAYER_WEBHOOK_SIGNING_PRIVATE_KEY: readEnvValue(
			path,
			"SECONDLAYER_WEBHOOK_SIGNING_PRIVATE_KEY",
		),
		SL_API_URL: readEnvValue(path, "SL_API_URL"),
		SL_API_KEY: readEnvValue(path, "SL_API_KEY"),
		ARCHIVE_SIGNING_PUBLIC_KEY: readEnvValue(
			path,
			"ARCHIVE_SIGNING_PUBLIC_KEY",
		),
	};
}
