/**
 * Generates the self-contained docker-compose used by `secondlayer setup` for a
 * production one-box install — Postgres + the Secondlayer runtime, with the
 * bundled-node and console profiles available.
 *
 * SOURCE OF TRUTH: this mirrors `docker/oss/docker-compose.yml`. The one
 * intentional difference is `secondlayer`/`console`: the checked-in file
 * `build:`s them from a repo checkout (`context: ../..`), which a CLI-only
 * install — `bun add -g @secondlayer/cli`, no monorepo present — doesn't have.
 * Here they're pinned to the published OSS images instead, the same swap
 * `devnet-compose.ts` makes for the devnet stack. Everything else (env var
 * names, defaults, profiles, healthchecks, third-party digest pins) is kept
 * byte-for-byte so the two never quietly diverge on what the runtime expects.
 *
 * This is a SEPARATE generator from `devnet-compose.ts`, not a shared module:
 * the two stacks have genuinely different topologies (devnet splits
 * api/indexer into two containers and disables the Hiro-mainnet fallbacks;
 * this is the one-box runtime image with bundled-node and console profiles).
 * Forcing a shared template would abstract over that difference rather than
 * express it. If you touch `docker/oss/docker-compose.yml`, update this file
 * (and `devnet-compose.ts`, if the change applies there too) in the same
 * change.
 */

import { DEFAULT_IMAGE_OWNER, DEFAULT_IMAGE_TAG } from "./devnet-compose.ts";

export { DEFAULT_IMAGE_OWNER, DEFAULT_IMAGE_TAG };

export interface OssComposeOptions {
	owner?: string;
	imageTag?: string;
}

/**
 * Written once and then left to `.env` for every subsequent value — the
 * compose file itself carries no secrets, only `${VAR:-default}` references,
 * exactly like `docker/oss/docker-compose.yml`. `secondlayer setup` writes the
 * resolved `.env` alongside it.
 */
export function buildOssCompose(opts: OssComposeOptions = {}): string {
	const owner = opts.owner ?? DEFAULT_IMAGE_OWNER;
	const tag = opts.imageTag ?? DEFAULT_IMAGE_TAG;
	const runtimeImage = `ghcr.io/${owner}/secondlayer-runtime:${tag}`;
	const consoleImage = `ghcr.io/${owner}/secondlayer-console:${tag}`;

	return `# Generated by \`secondlayer setup\` — do not edit by hand.
# Mirrors docker/oss/docker-compose.yml; see that file for the source of truth
# on env vars, profiles, and third-party digest pins. \`secondlayer\`/\`console\`
# are swapped from a repo build to the published OSS images (no checkout here).
name: secondlayer

services:
  postgres:
    image: postgres:17-alpine@sha256:d4bb0a8c1b7bb2e29f976d099e7bfb9a5d8858cffe9e46b35cd302cd1f1f8168
    environment:
      POSTGRES_USER: \${POSTGRES_USER:-secondlayer}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-secondlayer}
      POSTGRES_DB: \${POSTGRES_DB:-secondlayer}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "\${POSTGRES_PORT:-127.0.0.1:5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER:-secondlayer}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  secondlayer:
    image: ${runtimeImage}
    environment:
      INSTANCE_MODE: oss
      NETWORK: \${NETWORK:-\${STACKS_NETWORK:-mainnet}}
      STACKS_NETWORK: \${STACKS_NETWORK:-mainnet}
      NODE_MODE: \${NODE_MODE:-external}
      SECONDLAYER_ALLOW_UNDERSIZED: \${SECONDLAYER_ALLOW_UNDERSIZED:-false}
      DATABASE_URL: postgres://\${POSTGRES_USER:-secondlayer}:\${POSTGRES_PASSWORD:-secondlayer}@postgres:5432/\${POSTGRES_DB:-secondlayer}
      DATA_DIR: /data
      API_PORT: "3800"
      INDEXER_PORT: "3700"
      # See docker/oss/docker-compose.yml: API_PORT above is the *container*
      # port; \${API_PORT} in ports:/here is the *publish spec* from .env.
      LISTEN_HOST: "0.0.0.0"
      API_PUBLISH_ADDR: \${API_PORT:-127.0.0.1:3800}
      INSTANCE_TOKEN: \${INSTANCE_TOKEN:-}
      SECONDLAYER_SECRETS_KEY: \${SECONDLAYER_SECRETS_KEY:-}
      STREAMS_SIGNING_PRIVATE_KEY: \${STREAMS_SIGNING_PRIVATE_KEY:-}
      SECONDLAYER_WEBHOOK_SIGNING_PRIVATE_KEY: \${SECONDLAYER_WEBHOOK_SIGNING_PRIVATE_KEY:-}
      ALLOW_UNSIGNED_WEBHOOKS: \${ALLOW_UNSIGNED_WEBHOOKS:-false}
      LOG_LEVEL: \${LOG_LEVEL:-info}
      NODE_ENV: production
      STACKS_NODE_RPC_URL: \${STACKS_NODE_RPC_URL:-}
      OBSERVER_JOURNAL_ENABLED: \${OBSERVER_JOURNAL_ENABLED:-true}
      STREAMS_API_URL: http://127.0.0.1:3800
      STREAMS_INTERNAL_API_KEY: \${STREAMS_INTERNAL_API_KEY:-}
      SBTC_DECODER_ENABLED: \${SBTC_DECODER_ENABLED:-true}
      POX4_DECODER_ENABLED: \${POX4_DECODER_ENABLED:-true}
      BNS_DECODER_ENABLED: \${BNS_DECODER_ENABLED:-false}
      SUBGRAPH_SOURCE: \${SUBGRAPH_SOURCE:-streams-index}
      SUBGRAPH_INDEX_API_URL: http://127.0.0.1:3800
      BITCOIN_RPC_PASSWORD: \${BITCOIN_RPC_PASSWORD:-}
    ports:
      - "\${API_PORT:-127.0.0.1:3800}:3800"
      - "\${INDEXER_PORT:-127.0.0.1:3700}:3700"
    volumes:
      - subgraphs_data:/data/subgraphs
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3800/health"]
      interval: 30s
      timeout: 5s
      start_period: 40s
      retries: 3
    restart: unless-stopped

  console:
    image: ${consoleImage}
    environment:
      SL_API_URL: http://secondlayer:3800
      INSTANCE_TOKEN: \${INSTANCE_TOKEN:-}
      CONSOLE_TOKEN: \${CONSOLE_TOKEN:-}
      NODE_ENV: production
    ports:
      - "\${CONSOLE_PORT:-3801}:3801"
    depends_on:
      secondlayer:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3801/console"]
      interval: 30s
      timeout: 5s
      start_period: 15s
      retries: 3
    restart: unless-stopped
    profiles: ["console"]

  bitcoind:
    # Digest = kylemanna/bitcoind:latest as published 2026-07-20 — see
    # docker/oss/docker-compose.yml for why the digest is the real pin here.
    image: kylemanna/bitcoind:latest@sha256:86bbcaa99bf3bf3d5df7fd6d9217b3a41194db4c4e34385064f2cfc9fa7bdf91
    volumes:
      - \${BITCOIN_DATA_DIR:-./data/bitcoin}:/bitcoin/.bitcoin
    ports:
      - "127.0.0.1:8332:8332"
      - "8333:8333"
    healthcheck:
      test: ["CMD-SHELL", "bitcoin-cli -rpcuser=\${BITCOIN_RPC_USER:-stacks} -rpcpassword=\${BITCOIN_RPC_PASSWORD:-changeme} getblockchaininfo | grep -q '\\\"blocks\\\"' && [ $$(bitcoin-cli -rpcuser=\${BITCOIN_RPC_USER:-stacks} -rpcpassword=\${BITCOIN_RPC_PASSWORD:-changeme} getblockcount) -gt 666050 ]"]
      interval: 60s
      timeout: 15s
      start_period: 120s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 32G
    profiles: ["full-node"]

  stacks-node:
    # Consensus-critical — digest-pinned to 4.0.1. See docker/oss/docker-compose.yml.
    image: ghcr.io/stacks-network/stacks-core:4.0.1@sha256:ceb768f881ef52a1d2792a2b4a89d81e092b1df11293b04c31ce36613c3f9711
    volumes:
      - \${STACKS_DATA_DIR:-./data/stacks}:/stacks-blockchain/data
      - ./Config.toml:/stacks-blockchain/Config.toml:ro
    ports:
      - "20443:20443"
      - "20444:20444"
    restart: unless-stopped
    command: ["stacks-node", "start", "--config", "/stacks-blockchain/Config.toml"]
    profiles: ["stacks-node", "full-node"]

volumes:
  postgres_data:
  subgraphs_data:
`;
}

/**
 * The bundled node's `Config.toml`, mounted read-only by the `stacks-node`
 * service above. Mirrors `docker/oss/Config.toml` — same bootstrap peers,
 * same safe-by-default observer stanza (retries off, low timeout, so a
 * co-located signer is never starved by a stuck indexer).
 */
export function buildOssStacksConfigToml(opts: {
	network: "mainnet" | "testnet" | "devnet";
	bitcoinRpcPassword: string;
}): string {
	const mode = opts.network === "mainnet" ? "mainnet" : "testnet";
	return `[node]
working_dir = "/stacks-blockchain/data"
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
seed = ""
marf_compress = true
bootstrap_node = "02196f005965cebe6ddc3901b7b1cc1aa7a88f305bb8c5893456b8f9a605923893@seed.mainnet.hiro.so:20444,02539449ad94e6e6392d8c1deb2b4e61f80ae2a18964349bc14336d8b903c46a8c@cet.stacksnodes.org:20444,02ececc8ce79b8adf813f13a0255f8ae58d4357309ba0cedd523d9f1a306fcfb79@sgt.stacksnodes.org:20444,0303144ba518fe7a0fb56a8a7d488f950307a4330f146e1e1458fc63fb33defe96@est.stacksnodes.org:20444"

# Event observer points directly at the bundled indexer service, same docker
# network. Retries off / low timeout: a stuck indexer must never starve a
# co-located signer of block_proposal events. See docker/oss/Config.toml.
[[events_observer]]
endpoint = "secondlayer:3700"
events_keys = ["*"]
timeout_ms = 500
disable_retries = true

[burnchain]
chain = "bitcoin"
mode = "${mode}"
peer_host = "bitcoind"
username = "stacks"
password = "${opts.bitcoinRpcPassword}"
rpc_port = 8332
peer_port = 8333
`;
}

/** Mirrors `docker/oss/bitcoin.conf` — only the `full` node mode uses this. */
export function buildOssBitcoinConf(opts: { rpcPassword: string }): string {
	return `server=1
txindex=1
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0
rpcuser=stacks
rpcpassword=${opts.rpcPassword}
# Prune: 0 = archive (required for Stacks); set to 550+ only for pruned chains.
prune=0
dbcache=4096
`;
}
