import type { ClarityContract } from "../abi/functions";
import type {
  ExtractFunctionArgs,
  ExtractPublicFunctions,
  ExtractReadOnlyFunctions,
} from "../abi/extractors";

/**
 * Integration types for @stacks/connect
 *
 * Note: The actual contract interface implementations are generated by the CLI tool.
 * This module only exports type definitions for type-safe contract interactions.
 */

/**
 * Type that matches @stacks/connect contract call options
 */
export interface ContractCallParams {
  contractAddress: string;
  contractName: string;
  functionName: string;
  functionArgs: ReadonlyArray<unknown>;
}

/**
 * Type for read-only function calls
 */
export interface ReadOnlyCallParams {
  contractAddress: string;
  contractName: string;
  functionName: string;
  functionArgs: ReadonlyArray<unknown>;
}

/**
 * Type-safe contract interface type.
 * Maps public functions to ContractCallParams and read-only functions to ReadOnlyCallParams.
 */
export type ContractInterface<C extends ClarityContract> = {
  // Public functions return ContractCallParams
  [K in ExtractPublicFunctions<C>]: {
    (args: ExtractFunctionArgs<C, K>): ContractCallParams;
    (...args: unknown[]): ContractCallParams;
  };
} & {
  // Read-only functions return ReadOnlyCallParams
  [K in ExtractReadOnlyFunctions<C>]: {
    (args: ExtractFunctionArgs<C, K>): ReadOnlyCallParams;
    (...args: unknown[]): ReadOnlyCallParams;
  };
};

/**
 * Contract interface with metadata (address and name).
 */
export type ContractInterfaceWithMeta<C extends ClarityContract> =
  ContractInterface<C> & {
    contractAddress: string;
    contractName: string;
  };
