import { defineConfig } from "bunup";

export default defineConfig([
  {
    name: "main",
    entry: ["src/index.ts"],
    format: ["esm"],
    dts: true,
    splitting: false,
    sourcemap: "linked",
    minify: false,
    external: ["esbuild", "@secondlayer/clarity-types"],
    shims: true,
    target: "bun",
  },
  {
    name: "cli",
    entry: ["src/cli.ts"],
    format: ["esm"],
    dts: false,
    splitting: false,
    sourcemap: "linked",
    minify: false,
    external: ["esbuild", "@secondlayer/clarity-types"],
    shims: true,
    target: "bun",
  },
  {
    name: "plugins",
    entry: ["src/plugins/index.ts"],
    format: ["esm"],
    dts: true,
    splitting: false,
    sourcemap: "linked",
    minify: false,
    external: ["esbuild", "@secondlayer/clarity-types"],
    shims: true,
    target: "bun",
  },
  {
    name: "plugin-manager",
    entry: ["src/core/plugin-manager.ts"],
    format: ["esm"],
    dts: true,
    splitting: false,
    sourcemap: "linked",
    minify: false,
    external: ["esbuild", "@secondlayer/clarity-types"],
    shims: true,
    target: "bun",
  },
]);
