import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { buildOssCompose } from "../src/lib/oss-compose.ts";

const repo = join(import.meta.dir, "../../..");
const CACHE_COMMAND =
	'command: ["postgres", "-c", "shared_buffers=${POSTGRES_SHARED_BUFFERS:-1GB}"]';

/** The stock 128 MB cache stalls a full-chain sync on index reads; every
 *  oss compose a self-hoster can run sizes it from the same env var. */
describe("oss Postgres cache size", () => {
	test("repo compose files set shared_buffers from POSTGRES_SHARED_BUFFERS", () => {
		for (const rel of [
			"docker/oss/docker-compose.yml",
			"docker/oss/docker-compose.split.yml",
		]) {
			expect(readFileSync(join(repo, rel), "utf8")).toContain(CACHE_COMMAND);
		}
	});

	test("compose generated by setup matches the repo compose", () => {
		expect(buildOssCompose()).toContain(CACHE_COMMAND);
	});

	test("env example documents the knob", () => {
		expect(
			readFileSync(join(repo, "docker/oss/.env.example"), "utf8"),
		).toContain("POSTGRES_SHARED_BUFFERS=1GB");
	});
});
